#!/bin/bash
# this declares that current user is a sudoer
sudo tee /etc/sudoers.d/$USER <<END
END

# write the content of your script here
sudo npm install hexo-cli -g
mkdir Untitled
sudo apt-get install mysql
$ mysql -u root 
mysql> CREATE DATABASE wereareyou;
mysql> USE wereareyou;
mysql> CREATE TABLE Denuncia(Fecha datetime, Name VARCHAR(50), Image VARCHAR(150));
mysql> CREATE TABLE Pictures(Fecha datetime, Image VARCHAR(150));
sudo apt-get install python


# then to remove the sudo access from the current user
sudo /bin/rm /etc/sudoers.d/$USER
sudo -k
